[[main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1

[[main]]
	identifier = "blog"
	name = "Blog"
	url = "/blog"
	weight = 2

[[main]]
	identifier = "projects"
	name = "Projects"
	url = "/projects"
	weight = 3

[[main]]
	identifier = "photography"
	name = "Photography"
	url = "/photography"
	weight = 4

[[main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags"
	weight = 5

[[main]]
	identifier = "archive"
	name = "Archive"
	url = "/archive"
	weight = 6

# Social Media Configuration

[[social]]
	identifier = "email"
	name = "Email"
	url = "mailto:hello@jwoos.com"
	weight = 1

[[social]]
	identifier = "instagram"
	name = "Instagram"
	url = "https://www.instagram.com/shin.junwoo/"
	weight = 2

[[social]]
	identifier = "github"
	name = "GitHub"
	url = "https://github.com/jwoos"
	weight = 3
