permalink: /:title/
url: "http://jwoos.github.io"
full_name: "Jun Woo Shin"
first_name: "Jun Woo"
last_name: "Shin"
blog_title: "Jun Woo Shin"
author_img_name_path: ""
copyright_year: "2016"
google_analytics_code: ""
